version: '2'

services:
  gitlab:
    network_mode: "bridge"
    container_name: gitlab
    restart: always
    image: gitlab/gitlab-ce:latest
    ports:
    - "10080:80"
    - "10022:22"
    - "10443:443"
    volumes:
    - /data/gitlab/config:/etc/gitlab       
    - /data/gitlab/logs:/var/log/gitlab
    - /data/gitlab/data:/var/opt/gitlab
    - /data/certs:/etc/gitlab/ssl
    environment:
    - VIRTUAL_HOST=gitlab.docker.tolron.fr
    - VIRTUAL_PROTO=https
    - LETSENCRYPT_HOST=gitlab.docker.tolron.fr
    - LETSENCRYPT_EMAIL=sebastien@tolron.fr

    - GITLAB_HOST=https://gitlab.docker.tolron.fr;
