version: '2'

services:
  app:
    image: clue/h5ai
    container_name: downloads
    volumes:
      - "/data:/var/www"
    environment:
      - VIRTUAL_HOST=downloads.docker.tolron.fr
      - LETSENCRYPT_HOST=downloads.docker.tolron.fr
      - LETSENCRYPT_EMAIL=sebastien@tolron.fr
    network_mode: "bridge"

