version: '2'

services:
  app:
    image: clue/h5ai
    container_name: browser
    volumes:
      - "media:/var/www"
    environment:
      - VIRTUAL_HOST=browser.lobr.fr
    network_mode: "bridge"

volumes:
  media:
    external: true