version: '2'

services:
  server:
    image: jpetazzo/dockvpn
    container_name: vpn
    privileged: true
    ports:
      - "1194/udp:1194/udp"
      - "1443/tcp:443/tcp"
    network_mode: "bridge"

  config:
    image: jpetazzo/dockvpn
    container_name: vpn-config
    command: "serveconfig"
    volumes_from:
      - server
    ports:
      - "8080:8080"
    environment:
      - VIRTUAL_HOST=vpn.lobr.fr
      - VIRTUAL_PORT=8080
      - VIRTUAL_PROTO=https
      - CERT_NAME=none
    network_mode: "bridge"