version: '2'

services:
  app:
    image: linuxserver/sonarr
    container_name: sonarr
    ports:
      - "8989:8989"
    volumes:
      - "/dev/rtc:/dev/rtc:ro"
      - "media:/downloads"
      - "media:/tv"
    environment:
      - PUID=1000
      - PGID=1000
      - VIRTUAL_HOST=sonarr.lobr.fr
      - VIRTUAL_PORT=8989
      - LETSENCRYPT_HOST=sonarr.lobr.fr
      - LETSENCRYPT_EMAIL=loric.brevet@gmail.com
    network_mode: "bridge"

volumes:
  media:
    external: true