nginx:
  image: nginx
  volumes:
    - "./web:/usr/share/nginx/html"
  environment:
    - VIRTUAL_HOST=home.lobr.fr
    - VIRTUAL_PORT=80

gen:
  image: jwilder/docker-gen
  command: "-watch -only-exposed /etc/docker-gen/templates/template.html /etc/docker-gen/templates/index.html"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    - "./web:/etc/docker-gen/templates"