version: '2'

services:
  nginx:
    image: nginx
    container_name: home
    volumes:
      - "web:/usr/share/nginx/html"
    environment:
      - VIRTUAL_HOST=docker.tolron.fr
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=docker.tolron.fr
      - LETSENCRYPT_EMAIL=sebastien@tolron.fr
    network_mode: "bridge"

  gen:
    image: jwilder/docker-gen
    container_name: home-gen
    command: "-watch -only-exposed /etc/docker-gen/templates/template.html /web/index.html"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./template.html:/etc/docker-gen/templates/template.html"
      - "web:/web"
    network_mode: "bridge"

volumes:
  web:
    driver: local
