version: '2'

services:
  app:
    image: realms/realms-wiki
    container_name: note
    volumes:
      - "data:/tmp"
    environment:
      - VIRTUAL_HOST=note.lobr.fr
      - VIRTUAL_PORT=5000
    network_mode: "bridge"

volumes:
  data:
    driver: local