version: '2'

services:
  app:
    image: uifd/ui-for-docker
    container_name: docker-ui
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - VIRTUAL_HOST=docker-ui.docker.tolron.fr
      - LETSENCRYPT_HOST=docker-ui.docker.tolron.fr
      - LETSENCRYPT_EMAIL=sebastien@tolron.fr
    network_mode: "bridge"
