version: '2'

services:
  app:
    image: linuxserver/plex
    container_name: plex
    ports:
      - "32400:32400"
    volumes:
      - "./Preferences.xml:/config/Library/Application Support/Plex Media Server/Preferences.xml"
      - "/data:/data"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=plexpass
      - VIRTUAL_HOST=streaming.docker.tolron.fr
      - VIRTUAL_PORT=32400
      - LETSENCRYPT_HOST=streaming.docker.tolron.fr
      - LETSENCRYPT_EMAIL=sebastien@tolron.fr
    network_mode: "bridge"

