browser:
  image: clue/h5ai
  container_name: browser
  volumes:
    - "./data:/var/www"
  environment:
    - VIRTUAL_HOST=browser.lobr.fr

ftp:
  image: mcreations/ftp
  container_name: ftp
  volumes:
    - "./data:/data/admin"
  ports:
    - "21:21"
    - "65000-65004:65000-65004"
  environment:
    - FTP_USER=admin
    - FTP_PASS=media012
    - HOST=lobr.fr
    - PASV_MIN_PORT=65000
    - PASV_MAX_PORT=65004

pydio:
  image: linuxserver/pydio
  container_name: pydio
  links:
    - pydio-db
  volumes:
    - "./data:/data/files"
    - "/etc/localtime:/etc/localtime:ro"
  environment:
    - PUID=1000
    - PGID=1000
    - VIRTUAL_HOST=pydio.lobr.fr
    - VIRTUAL_PORT=443
    - VIRTUAL_PROTO=https

pydio-db:
  image: mysql
  container_name: pydio-db
  environment:
    - MYSQL_ROOT_PASSWORD=pydio
    - MYSQL_DATABASE=pydio

deluge:
  image: linuxserver/deluge
  container_name: deluge
  ports:
    - "8112:8112"
    - "58846:58846"
  volumes:
    - "./data/Downloads:/downloads"
  environment:
    - PUID=1000
    - PGID=1000
    - VIRTUAL_HOST=deluge.lobr.fr
    - VIRTUAL_PORT=8112

plex:
  image: linuxserver/plex
  container_name: plex
  ports:
    - "32400:32400"
  volumes:
    - "./data:/data"
  environment:
    - PUID=1000
    - PGID=1000
    - VERSION=plexpass
    - VIRTUAL_HOST=plex.lobr.fr
    - VIRTUAL_PORT=32400

couchpotato:
  image: linuxserver/couchpotato
  container_name: couchpotato
  ports:
    - "5050:5050"
  volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "./data/Downloads:/downloads"
    - "./data/Movies:/movies"
  environment:
    - PUID=1000
    - PGID=1000
    - VIRTUAL_HOST=couchpotato.lobr.fr
    - VIRTUAL_PORT=5050

sonarr:
  image: linuxserver/sonarr
  container_name: sonarr
  ports:
    - "8989:8989"
  volumes:
    - "/dev/rtc:/dev/rtc:ro"
    - "./data/Downloads:/downloads"
    - "./data/Series:/tv"
  environment:
    - PUID=1000
    - PGID=1000
    - VIRTUAL_HOST=sonarr.lobr.fr
    - VIRTUAL_PORT=8989

sickrage:
  image: linuxserver/sickrage
  container_name: sickrage
  ports:
    - "8081:8081"
  volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "./data/Downloads:/downloads"
    - "./data/Series:/tv"
  environment:
    - PUID=1000
    - PGID=1000
    - VIRTUAL_HOST=sickrage.lobr.fr
    - VIRTUAL_PORT=8081