version: '2'

services:
  app:
    image: linuxserver/couchpotato
    container_name: couchpotato
    ports:
      - "5050:5050"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/data:/downloads"
      - "/data:/movies"
    environment:
      - PUID=1000
      - PGID=1000
      - VIRTUAL_HOST=couchpotato.docker.tolron.fr
      - VIRTUAL_PORT=5050
      - LETSENCRYPT_HOST=couchpotato.docker.tolron.fr
      - LETSENCRYPT_EMAIL=sebastien@tolron.fr
    network_mode: "bridge"

