app:
  image: linuxserver/couchpotato
  container_name: couchpotato
  ports:
    - "5050:5050"
  volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "../data/media/Downloads:/downloads"
    - "../data/media/Movies:/movies"
  environment:
    - PUID=1000
    - PGID=1000
    - VIRTUAL_HOST=couchpotato.lobr.fr
    - VIRTUAL_PORT=5050