version: '2'

services:
  app:
    image: linuxserver/sickrage
    container_name: sickrage
    ports:
      - "8082:8082"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config.ini:/config/config.ini"
      - "/data:/downloads"
      - "/data:/tv"
    environment:
      - PUID=1000
      - PGID=1000
      - VIRTUAL_HOST=sickrage.docker.tolron.fr
      - VIRTUAL_PORT=8082
      - LETSENCRYPT_HOST=sickrage.docker.tolron.fr
      - LETSENCRYPT_EMAIL=sebastien@tolron.fr
    network_mode: "bridge"

