version: '2'

services:
  app:
    image: linuxserver/sickrage
    container_name: sickrage
    ports:
      - "8081:8081"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config.ini:/config/config.ini"
      - "media:/downloads"
      - "media:/tv"
    environment:
      - PUID=1000
      - PGID=1000
      - VIRTUAL_HOST=sickrage.lobr.fr
      - VIRTUAL_PORT=8081
    network_mode: "bridge"

volumes:
  media:
    external: true