app:
  image: linuxserver/sickrage
  container_name: sickrage
  ports:
    - "8081:8081"
  volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "../data/media/Downloads:/downloads"
    - "../data/media/Series:/tv"
  environment:
    - PUID=1000
    - PGID=1000
    - VIRTUAL_HOST=sickrage.lobr.fr
    - VIRTUAL_PORT=8081