generate_certificate:
  build: .
  container_name: generate-certificate
  volumes:
    - ./certs:/certificates
  environment:
    - SERVER=lobr.fr
    - EMAIL=loric.brevet@gmail.com
    - ORGANIZATION=lobr
    - COUNTRY_CODE=FR
    - STATE=France
    - LOCALITY=Lyon

nginx:
  image: jwilder/nginx-proxy
  ports:
    - "8090:80"
    - "443:443"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    - "./certs:/etc/nginx/certs"
  environment:
    - DEFAULT_HOST=home.lobr.fr