version: '2'

services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "certs:/etc/nginx/certs:ro"
      - "vhost:/etc/nginx/vhost.d"
      - "challenge:/usr/share/nginx/html"
      - "./passwords:/etc/nginx/htpasswd"
      - "./proxy.conf:/etc/nginx/proxy.conf"
    environment:
      - DEFAULT_HOST=home.lobr.fr
    network_mode: "bridge"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "certs:/etc/nginx/certs:rw"
      - "vhost:/etc/nginx/vhost.d"
      - "challenge:/usr/share/nginx/html"
    volumes_from:
      - nginx
    network_mode: "bridge"

volumes:
  certs:
    driver: local
  vhost:
    driver: local
  challenge:
    driver: local