version: '2'

services:
  app:
    image: realms/realms-wiki
    container_name: notes
    volumes:
      - "data:/tmp"
    environment:
      - VIRTUAL_HOST=notes.lobr.fr
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=notes.lobr.fr
      - LETSENCRYPT_EMAIL=loric.brevet@gmail.com
    network_mode: "bridge"

volumes:
  data:
    driver: local