app:
  image: linuxserver/deluge
  container_name: deluge
  ports:
    - "8112:8112"
    - "58846:58846"
  volumes:
    - "./config:/config"
    - "../data/media/Downloads:/downloads"
  environment:
    - PUID=1000
    - PGID=1000
    - VIRTUAL_HOST=deluge.lobr.fr
    - VIRTUAL_PORT=8112