version: '2'

services:
  app:
    image: sspreitzer/shellinabox
    container_name: shell
    environment:
      - VIRTUAL_HOST=shell.docker.tolron.fr
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=shell.docker.tolron.fr
      - LETSENCRYPT_EMAIL=sebastien@tolron.fr
      - SIAB_SUDO=true
      - SIAB_USER=admin
      - SIAB_PASSWORD=terminal012
    network_mode: "bridge"
