version: '2'

services:
  app:
    image: francescou/docker-compose-ui
    container_name: compose-ui
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "..:/opt/docker-compose-projects"
    environment:
      - VIRTUAL_HOST=compose-ui.lobr.fr
    network_mode: "bridge"