app:
  image: francescou/docker-compose-ui:1.0.RC1
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "..:/opt/docker-compose-projects:ro"
  environment:
    - VIRTUAL_HOST=compose.lobr.fr